branches:
  - release
verifyConditions:
  - 'semantic-release-chrome'
  - 'semantic-release-firefox'
  - '@semantic-release/github'
prepare:
  # Create Chrome ZIP
  - path: semantic-release-chrome
    distFolder: &distFolder dist
    asset: &chromeZipPath link-preview-sidebar.zip
  # Create Firefox xpi and zip sources
  - path: semantic-release-firefox
    distFolder: *distFolder
    xpiPath: &firefoxXpiPath svg-screenshots-firefox.xpi
    sourcesArchivePath: &sourcesZipPath sources.zip
    sourcesGlobOptions:
      dot: true # Files like .assetWrapper.js are needed to build
      ignore:
        - .cache
        - .cache/**
        - .git
        - .git/**
        - .github
        - .github
        - .github/**
        - .github/**
        - .npmrc # This is added by semantic-release and would cause npm install to fail for the reviewer because it references NPM_TOKEN
        - dist
        - dist/**
        - node_modules
        - node_modules/**
        - *sourcesZipPath
        - web-ext-artifacts
        - web-ext-artifacts/**
publish:
  # Publish to GitHub releases for sideloading
  - path: '@semantic-release/github'
    assets:
      - path: *chromeZipPath
      - path: *firefoxXpiPath
  # Publish the the Chrome web store
  - path: semantic-release-chrome
    asset: *chromeZipPath
    extensionId: nfakpcpmhhilkdpphcjgnokknpbpdllg
  # Publish to Mozilla Add-on store
  - path: semantic-release-firefox
    xpiPath: *firefoxXpiPath
    distFolder: *distFolder
    addOnSlug: svg-screenshots
    notesToReviewer: |
      This extension is open source at https://github.com/felixfbecker/svg-screenshots

      Needed to build:
      NodeJS ^15.2.0
      NPM ^7.0.8

      Install dependencies with `npm install`.
      To build the extension into the dist/ folder run: npm run build
      To then build an extension ZIP for Firefox, run afterwards: npm run firefox:build
      The extension ZIP will be placed in `web-ext-artifacts/`.

      The extension contributes an action button that opens a popup. From there, you can select further actions to take a screenshot of the current page (Example: www.google.com).

      Permissions:
      - The extension needs the all_urls permission because it needs to fetch images and fonts from webpages in the background page to inline them as Base64 into the SVG.
      - It uses `storage` to persist user settings.

      The warning about usage of the `Function` constructor is a popular polyfill for Function.prototype.bind in the dependency chain.
