branches:
  - release
verifyConditions:
  # - 'semantic-release-chrome'
  - '@semantic-release/github'
prepare:
  # Create Chrome ZIP
  - path: semantic-release-chrome
    distFolder: &distFolder dist
    asset: &chromeZipPath link-preview-sidebar-chrome.zip
publish:
  # Publish to GitHub releases for sideloading
  - path: '@semantic-release/github'
    assets:
      - path: *chromeZipPath
  # Publish the the Chrome web store
  # - path: semantic-release-chrome
  #   asset: *chromeZipPath
  #   extensionId: cdnefgebicfnnnjmbnlldhfjmcblfhob